FROM golang:1.25-bookworm AS build
RUN apt-get update && apt-get install -y make nodejs npm git
WORKDIR /src
COPY . /src
RUN make build
FROM debian:bookworm-slim
COPY --from=build /src/prometheus /bin/prometheus
COPY --from=build /src/promtool /bin/promtool
